### ISSUE TITLE
Support for non-apps in location db

### ISSUE THREAD

**Issue by clburlison** [univ-of-utah-marriott-library-apple/privacy_services_manager#12]
This feature request is closely related to #10. Any chance you could add the ``--admin`` flag and allow non-app files to be added into the location database. I tried but my python is not very good. Thanks for the great project!

**Comment by pdarragh** [comment]
Hello @clburlison,

Unfortunately, I'm not sure that it's possible to add the `--admin` flag for the location database. If you look in the `location_services.py` file ([here's a link](https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/blob/master/privacy_services_management/location_services.py)), around line 85 is where you'll start to see all the information needed to modify the location services property list.

It's been a while, but as I recall the system very much wants to know all of the information that you see the script add there - particularly the bundle identifier.

I will attempt to modify this to allow non-app files and I'll report back to you the findings, just to be sure. But like I said, I think the location services daemon was a bit more particular about these things than the regular privacy services one. Still, it's definitely worth a look.

Thanks for liking our project! It's always good to hear other people are using what we've put out here.
Pierce

**Comment by uurazzle** [comment]
Hello Clayton

Does you non-app working use the native OS X UI?

 If so, can you use more details in the software/binary you want to use location services and web link to download it. Then we have something to test against

Sent from my iPad

On Feb 12, 2015, at 2:22 AM, Clayton Burlison <notifications@github.com<mailto:notifications@github.com>> wrote:


This feature request is closely related to #10<https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/issues/10>. Any chance you could add the --admin flag and allow non-app files to be added into the location database. I tried but my python is not very good. Thanks for the great project!

**Comment by clburlison** [comment]
The binary does work using the native OS X UI. You can build the binary yourself using this project. https://github.com/lindes/get-location or use this [pre-compiled binary](https://dl.dropboxusercontent.com/u/4223848/get-location). During the initial ``make`` command OS X asks you if you wish to would like to give access to the binary. Afterward the ``/var/db/locationd/clients.plist`` looks like below:

````plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.icloud.findmydeviced</key>
	<dict/>
	<key>com.apple.locationd.executable-/Users/clburlison/Dropbox/Public/get-location</key>
	<dict>
		<key>Authorized</key>
		<true/>
		<key>BundleId</key>
		<string>com.apple.locationd.executable-/Users/clburlison/Dropbox/Public/get-location</string>
		<key>Executable</key>
		<string>/Users/clburlison/Dropbox/Public/get-location</string>
		<key>Hide</key>
		<integer>1</integer>
		<key>Registered</key>
		<string>/Users/clburlison/Dropbox/Public/get-location</string>
		<key>Requirement</key>
		<string>cdhash H"2798b9d685e316627870c9a9e9e5643e5d1c3294"</string>
		<key>Whitelisted</key>
		<false/>
	</dict>
</dict>
</plist>
````

**Comment by uurazzle** [comment]
Ok, thx. We will investigate and see if we can update the code to support it.

On Feb 12, 2015, at 7:08 AM, Clayton Burlison <notifications@github.com<mailto:notifications@github.com>> wrote:


The binary does work using the native OS X UI. You can build the binary yourself using this project. https://github.com/lindes/get-location or use this pre-compiled binary<https://dl.dropboxusercontent.com/u/4223848/get-location>. During the initial make command OS X asks you if you wish to would like to give access to the binary. Afterward the /var/db/locationd/clients.plist looks like below:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.icloud.findmydeviced</key>
    <dict/>
    <key>com.apple.locationd.executable-/Users/clburlison/Dropbox/Public/get-location</key>
    <dict>
        <key>Authorized</key>
        <true/>
        <key>BundleId</key>
        <string>com.apple.locationd.executable-/Users/clburlison/Dropbox/Public/get-location</string>
        <key>Executable</key>
        <string>/Users/clburlison/Dropbox/Public/get-location</string>
        <key>Hide</key>
        <integer>1</integer>
        <key>Registered</key>
        <string>/Users/clburlison/Dropbox/Public/get-location</string>
        <key>Requirement</key>
        <string>cdhash H"2798b9d685e316627870c9a9e9e5643e5d1c3294"</string>
        <key>Whitelisted</key>
        <false/>
    </dict>
</dict>
</plist>

—
Reply to this email directly or view it on GitHub<https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/issues/12#issuecomment-74075805>.

Thanks:

Richard Glaser
University of Utah, Marriott Library ITS
richard.glaser@utah.edu<mailto:richard.glaser@utah.edu>

**Comment by clburlison** [comment]
Thank you! Worked perfectly. :+1:

**Comment by pdarragh** [comment]
Glad to hear it! If you have any other issues or questions, just let us know. Thanks!
