### ISSUE TITLE
El Capitan support

### ISSUE THREAD

**Issue by pdarragh** [univ-of-utah-marriott-library-apple/privacy_services_manager#27]
TCC services require an additional field `policy_id`, which appear as the new seventh column (moving the primary key to the eighth). This column can be populated with `NULL` to no adverse effects.

**Comment by pdarragh** [comment]
@dhoer I created an issue here so it can be tracked separately.

Not only does it appear that there's an additional field in the `access` table, but there's are new `policies` and `active_policy` tables to interact with and some other changes to the database.

**Comment by dhoer** [comment]
Nice!
