### ISSUE TITLE
Release 1.6.8 dmg is missing

### ISSUE THREAD

**Issue by dhoer** [univ-of-utah-marriott-library-apple/privacy_services_manager#35]
Release 1.6.9 is broken and I can't fall back to 1.6.8 that worked but had a bug I can work around.

**Comment by dhoer** [comment]
@pdarragh @uurazzle I just want to clarify why I wrote this up as an issue.  When a release happens, it is assumed that the artifacts created are immutable.  So when you delete it, it breaks stuff like my build pipeline. It makes the whole system that depends on that artifact fragile.  Some systems are complex and it may be a long time before they can update to a newer version, if they update at all.

So please let me know if you plan to alway keep your releases indefinitely, going forward, or plan to delete them.  If it is the latter, then I can't use your releases and will fork this repo.

Thanks,
Dennis

**Comment by pdarragh** [comment]
@dhoer,

First of all, let me say that I'm really sorry to hear about the issue. Obviously I never intend for things to get pushed that will cause problems, but invariably it ends up happening.

I'll be perfectly straightforward and tell you that I'm still a relatively green developer, and I'm still figuring out how best to manage my repositories to ensure they're as helpful as possible to everyone who uses them. I hadn't thoroughly considered the value in ensuring previous releases stay available indefinitely, but clearly that was not well-considered. (And of course hindsight is 20/20, so it seems painfully obvious to me now.)

I'm out of the office until later today, but I wanted you to be sure that I'm aware of your problem and will do everything I can to make it better for you. As soon as I get in, I'll fix the issues in the current build as well as figure out what I'm going to do about previous builds' release availability. At the very least, I will have a 1.6.8 DMG available for you before the end of the working day MST.

While the software we're providing is free and open source, and therefore doesn't have the same expectations from its users as proprietary software, I want to convey to you that I intend to rectify this issue as soon as I am able, and I will strive to reduce the incidence of further issues going forward. I appreciate that you use our software at all, and I don't want you to lose faith in our ability to continue maintaining this repository. I will absolutely ensure that we will keep releases indefinitely in the future.

As always, thank you for the feedback. I really do appreciate it.

Regards,
Pierce

**Comment by pdarragh** [comment]
Additionally, something I just considered: it should be possible to retrieve the old DMG by locating the old file in the `pkg` directory in the previous commits. [Here is a link](https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/blob/368cefdbd14beba56a4386ecd9edcba22bc1db2c/pkg/Privacy%20Services%20Management%20%5B1.6.8%5D.dmg) that should (hopefully) work for it. That's commit 368cefdbd14beba56a4386ecd9edcba22bc1db2c.

**Comment by dhoer** [comment]
Thanks for your response. Supporting an open source system is the best way to learn the dos and don'ts.  So no worries.  ;-)

I don't want to change the core code of the chef cookbook. It is built to just require a version and it will fetch it from the repository and install it.  
https://github.com/dhoer/chef-privacy_services_manager/blob/master/attributes/default.rb#L1

So I plan to wait for an update.

Here are some tips for supporting open source (some you might already know):
- Version based on http://semver.org. 
- Have unit tests  (python has several testing to choose from like pytest).  
- Since this is open source, use a tool like travis-ci (its free) to run those tests before you release: http://docs.travis-ci.com/user/languages/python/
- Integration test - This might be more tricky. You can use the https://github.com/dhoer/chef-privacy_services_manager cookbook to test.  It spins up a mac image (yosemite) and adds, enables, disables, and removes accessibility applications. That is what caught this current issue. And the tests can be improved to cover the other 5 services.  It requires vmware-fusion, vagrant and chef.  If you want, I can spend 30-minutes to an hour getting you setup. Just make sure you have vmware-fusion installed before we start.  Vagrant and ChefDK are relatively easy to setup.

**Comment by pdarragh** [comment]
Okay, I fixed #34 with the most recent commit and added a new release, *and* I tested it thoroughly in advance this time (like I should've done in the first place).

Sorry again about all the trouble.

Thanks for the pointers! I will be checking into those, and I'll be sure to let you know if I need any help with the integration stuff.

It doesn't seem to be very easy to go back and re-add binaries to previous releases... but I will be sure to keep releases indefinitely going forward. I hope that's an alright compromise?

**Comment by dhoer** [comment]
That will work.  Thanks for the quick turn-around.

**Comment by dhoer** [comment]
Hey, the name has changed as well from having underscores to periods: Privacy.Services.Management.1.6.10.dmg
Privacy_Services_Management_1.6.8.dmg

Was that intentional?  In order for my downloads to work, the name convention has to alway remain the same.

**Comment by dhoer** [comment]
Can you please let me know if you plan to use periods going forward, so I know to change my code?  Or will you release with underscores?

**Comment by uurazzle** [comment]
IMHO, for human readability we should use "_" vs "."

Privacy_Services_Management_1.6.10.dmg

On Jul 31, 2015, at 2:49 PM, Dennis Hoer <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, the name has changed as well from having underscores to periods: Privacy.Services.Management.1.6.10.dmg
Privacy_Services_Management_1.6.8.dmg

Was that intentional? In order for my downloads to work, the name convention has to alway remain the same.

—
Reply to this email directly or view it on GitHub<https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/issues/35#issuecomment-126809207>.

Thanks:

Richard Glaser
University of Utah, Marriott Library ITS
richard.glaser@utah.edu<mailto:richard.glaser@utah.edu>

**Comment by dhoer** [comment]
Or you make it mavenish:
${artifactId}-${version} = privacy_services_manager-1.6.11

**Comment by pdarragh** [comment]
@dhoer sorry about that, I usually update those right after I post them. By default my packages have spaces in their names, but GitHub automatically translates those to periods when they're uploaded as a release. Generally I just immediately rename them to use underscores, which is what @uurazzle and I decided on a while ago. So you can expect underscores in the future.

**Comment by dhoer** [comment]
You might try looking at this to automate it: https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by uurazzle** [comment]
That looks good to me, thx for the suggestion.

On Jul 31, 2015, at 3:17 PM, Dennis Hoer <notifications@github.com<mailto:notifications@github.com>> wrote:


Or you make it mavenish:
${artifactId}-${version} = privacy_services_manager-1.6.11

—
Reply to this email directly or view it on GitHub<https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/issues/35#issuecomment-126814185>.

Thanks:

Richard Glaser
University of Utah, Marriott Library ITS
richard.glaser@utah.edu<mailto:richard.glaser@utah.edu>

**Comment by dhoer** [comment]
Everything is looking good.  Thanks again
