### ISSUE TITLE
NameError: name 'no_check' is not defined

### ISSUE THREAD

**Issue by mciara** [univ-of-utah-marriott-library-apple/privacy_services_manager#42]
I'm using Privacy Services Manager, version 1.7.0 and I get this error when trying to add something:
```
NameError: name 'no_check' is not defined
```
It works only with `--no-check-app` flag.

**Comment by pdarragh** [comment]
@mciara sorry to hear that! Looks like I didn't change something properly in the last update... I'll have a fix out for that by noon tomorrow MST.

**Comment by mciara** [comment]
@pdarragh Thanks!

**Comment by pdarragh** [comment]
Hey @mciara,

I don't seem to be able to reproduce your issue. I've tried adding, disabling, and removing both `--no-check-app` and `--no-check-bin` in the various services, and all of my tests seemed to work as expected. Would you post the exact command you're using that's giving you this error? It's probably an edge case I'm not thinking of.

**Comment by mciara** [comment]
The command I run: 
```
~ ❯❯❯ privacy_services_manager.py  add calendar Fantastical
INFO: ################################################################################
Privacy Services Manager, version 1.7.0

    service:  calendar
    action:   add
    app(s):   ['Fantastical']
    user:     N/A
    template: False
    language: N/A

ERROR: NameError: name 'no_check' is not defined
```

**Comment by pdarragh** [comment]
Oh, yep. I didn't even think to test the case without `--no-check-app` or `--no-check-bin` being given. That was silly.

It's been resolved and I'm merging the fix into the master branch today after adjusting some code for #37. Look for a 1.7.2 release in a couple hours.

**Comment by pdarragh** [comment]
Change of plans: I'm merging your fix in earlier than expected. Can't seem to pin down the issue in #37 as quickly as I had hoped.

**Comment by mciara** [comment]
Thanks @pdarragh for the quick fix. Version 1.7.1 works fine.
